// AUTOMATISK GENERERT – IKKE REDIGER FOR HÅND
// Kjør: node scripts/gen-flags-assets.mjs
export const FLAGS_ASSETS: Record<string, any> = {
  "algerie": require("@/assets/flags/algerie.png"),
  "andorra": require("@/assets/flags/andorra.png"),
  "austria": require("@/assets/flags/austria.png"),
  "brazil": require("@/assets/flags/brazil.png"),
  "canada": require("@/assets/flags/canada.png"),
  "china": require("@/assets/flags/china.png"),
  "finland": require("@/assets/flags/finland.png"),
  "gambia": require("@/assets/flags/gambia.png"),
  "germany": require("@/assets/flags/germany.png"),
  "greece": require("@/assets/flags/greece.png"),
  "hungary": require("@/assets/flags/hungary.png"),
  "iceland": require("@/assets/flags/iceland.png"),
  "italy": require("@/assets/flags/italy.png"),
  "japan": require("@/assets/flags/japan.png"),
  "latvia": require("@/assets/flags/latvia.png"),
  "lithuania": require("@/assets/flags/lithuania.png"),
  "netherlands": require("@/assets/flags/netherlands.png"),
  "norway": require("@/assets/flags/norway.png"),
  "pakistan": require("@/assets/flags/pakistan.png"),
  "rumenia": require("@/assets/flags/rumenia.png"),
  "russia": require("@/assets/flags/russia.png"),
  "serbia": require("@/assets/flags/serbia.png"),
  "spain": require("@/assets/flags/spain.png"),
  "sweden": require("@/assets/flags/sweden.png"),
  "uk": require("@/assets/flags/uk.png"),
  "ukraine": require("@/assets/flags/ukraine.png"),
};
