import type { Q } from "./types";

export const LIGHTNING_BANKS: Record<"sport" | "kunst" | "historie" | "musikk", Q[]> = {
  sport: [
    { id: "sp01", text: "Hvor mange spillere har et fotballag på banen?",
      options: [{ id:"a",label:"9"},{ id:"b",label:"10"},{ id:"c",label:"11"},{ id:"d",label:"12"}],
      correctId: "c" },
    { id: "sp02", text: "Hvilket land arrangerer Tour de France?",
      options: [{ id:"a",label:"Italia"},{ id:"b",label:"Frankrike"},{ id:"c",label:"Spania"},{ id:"d",label:"Belgia"}],
      correctId: "b" },
    { id: "sp03", text: "Hva heter sporten der man kaster en liten stein på isen og feier foran?",
      options: [{ id:"a",label:"Curling"},{ id:"b",label:"Kjelkehockey"},{ id:"c",label:"Bandy"},{ id:"d",label:"Ishocurl"}],
      correctId: "a" },
    { id: "sp04", text: "Hvor mange poeng gir en straffescoring i håndball?",
      options: [{ id:"a",label:"1"},{ id:"b",label:"2"},{ id:"c",label:"3"},{ id:"d",label:"4"}],
      correctId: "a" },
    { id: "sp05", text: "Hvilket utstyr trenger du for å spille badminton?",
      options: [{ id:"a",label:"Kølle og fjærball"},{ id:"b",label:"Ball og hanske"},{ id:"c",label:"Kjegler"},{ id:"d",label:"Slegge"}],
      correctId: "a" },
    { id: "sp06", text: "Hvilken idrett er Marit Bjørgen kjent for?",
      options: [{ id:"a",label:"Skihopp"},{ id:"b",label:"Langrenn"},{ id:"c",label:"Kombinert"},{ id:"d",label:"Alpint"}],
      correctId: "b" },
    { id: "sp07", text: "Hva kalles den raskeste løpsdistansen i friidrett?",
      options: [{ id:"a",label:"800 meter"},{ id:"b",label:"100 meter"},{ id:"c",label:"1500 meter"},{ id:"d",label:"Maraton"}],
      correctId: "b" },
    { id: "sp08", text: "Hvor mange sett må du vinne i en vanlig tenniskamp (best av tre)?",
      options: [{ id:"a",label:"1"},{ id:"b",label:"2"},{ id:"c",label:"3"},{ id:"d",label:"5"}],
      correctId: "b" },
    { id: "sp09", text: "I hvilken idrett brukes puck?",
      options: [{ id:"a",label:"Bandy"},{ id:"b",label:"Ishockey"},{ id:"c",label:"Rugby"},{ id:"d",label:"Cricket"}],
      correctId: "b" },
    { id: "sp10", text: "Hva er målet i bowling?",
      options: [{ id:"a",label:"Treffe kjeglene"},{ id:"b",label:"Treffe ramma"},{ id:"c",label:"Treffe streken"},{ id:"d",label:"Treffe veggen"}],
      correctId: "a" },
    { id: "sp11", text: "Hva kalles en fulltreffer i dart (tre ganger 20)?",
      options: [{ id:"a",label:"Bullseye"},{ id:"b",label:"Triple 20"},{ id:"c",label:"Double 20"},{ id:"d",label:"Shanghai"}],
      correctId: "b" },
    { id: "sp12", text: "Hvilken idrett utøves på en bane med hull og flagg?",
      options: [{ id:"a",label:"Golf"},{ id:"b",label:"Krokket"},{ id:"c",label:"Baseball"},{ id:"d",label:"Cricket"}],
      correctId: "a" },
    { id: "sp13", text: "Hvor mange minutter varer en ordinær fotballkamp (uten tillegg)?",
      options: [{ id:"a",label:"60"},{ id:"b",label:"80"},{ id:"c",label:"90"},{ id:"d",label:"100"}],
      correctId: "c" },
    { id: "sp14", text: "Hvilket land er kjent for sporten sumobryting?",
      options: [{ id:"a",label:"Kina"},{ id:"b",label:"Japan"},{ id:"c",label:"Sør-Korea"},{ id:"d",label:"Thailand"}],
      correctId: "b" },
    { id: "sp15", text: "Hva betyr 'offside' i fotball?",
      options: [{ id:"a",label:"Ball utenfor sidelinjen"},{ id:"b",label:"Spiller forbi siste forsvarer idet ballen spilles"},{ id:"c",label:"Feil innkast"},{ id:"d",label:"Takling bakfra"}],
      correctId: "b" },
  ],
  kunst: [
    { id:"ku01", text:"Hvem malte «Mona Lisa»?",
      options:[{id:"a",label:"Michelangelo"},{id:"b",label:"Leonardo da Vinci"},{id:"c",label:"Rafael"},{id:"d",label:"Botticelli"}],
      correctId:"b" },
    { id:"ku02", text:"Hvilken norsk kunstner malte «Skrik»?",
      options:[{id:"a",label:"Nikolai Astrup"},{id:"b",label:"Harald Sohlberg"},{id:"c",label:"Edvard Munch"},{id:"d",label:"Christian Krohg"}],
      correctId:"c" },
    { id:"ku03", text:"Hva kalles små fargede glassbiter i bilder i kirker?",
      options:[{id:"a",label:"Fresker"},{id:"b",label:"Mosaikk"},{id:"c",label:"Tempera"},{id:"d",label:"Pastell"}],
      correctId:"b" },
    { id:"ku04", text:"Hvilket materiale brukes tradisjonelt i skulpturer av Michelangelo?",
      options:[{id:"a",label:"Bronse"},{id:"b",label:"Tre"},{id:"c",label:"Marmor"},{id:"d",label:"Leire"}],
      correctId:"c" },
    { id:"ku05", text:"Hva heter billedkunstens tre grunnfarger i tradisjonell teori?",
      options:[{id:"a",label:"Rød, blå, gul"},{id:"b",label:"Rød, grønn, blå"},{id:"c",label:"Cyan, magenta, gul"},{id:"d",label:"Svart, hvit, grå"}],
      correctId:"a" },
    { id:"ku06", text:"Hvilken by huser museet Louvre?",
      options:[{id:"a",label:"Roma"},{id:"b",label:"Paris"},{id:"c",label:"London"},{id:"d",label:"Madrid"}],
      correctId:"b" },
    { id:"ku07", text:"Hva kalles maleteknikken med vannfarger på papir?",
      options:[{id:"a",label:"Oljemaling"},{id:"b",label:"Akvarell"},{id:"c",label:"Gouache"},{id:"d",label:"Fresco"}],
      correctId:"b" },
    { id:"ku08", text:"Hvilken kunstretning er Pablo Picasso mest kjent for?",
      options:[{id:"a",label:"Kubisme"},{id:"b",label:"Impresjonisme"},{id:"c",label:"Surrealisme"},{id:"d",label:"Barokk"}],
      correctId:"a" },
    { id:"ku09", text:"Hva kalles kunsten å brette papirfigurer?",
      options:[{id:"a",label:"Origami"},{id:"b",label:"Ikebana"},{id:"c",label:"Calligrafi"},{id:"d",label:"Sumi-e"}],
      correctId:"a" },
    { id:"ku10", text:"Hvilket norsk museum viser «Vinternatt i Rondane»?",
      options:[{id:"a",label:"Nasjonalmuseet"},{id:"b",label:"Munchmuseet"},{id:"c",label:"Bergen Kunstmuseum"},{id:"d",label:"KODE"}],
      correctId:"a" },
    { id:"ku11", text:"Hvilket verktøy bruker man for å skjære i linoleum til trykk?",
      options:[{id:"a",label:"Meisel"},{id:"b",label:"Kniv"},{id:"c",label:"U-jern"},{id:"d",label:"Børste"}],
      correctId:"c" },
    { id:"ku12", text:"Hva kalles kunsten å skrive vakker skrift?",
      options:[{id:"a",label:"Kalligrafi"},{id:"b",label:"Typografi"},{id:"c",label:"Litografi"},{id:"d",label:"Paleografi"}],
      correctId:"a" },
    { id:"ku13", text:"Hvilken norsk kunstner er kjent for ‘Furunes’-portrettene i hullmønster?",
      options:[{id:"a",label:"Mari Slaattelid"},{id:"b",label:"Vebjørn Sand"},{id:"c",label:"Anne-Karin Furunes"},{id:"d",label:"Håkon Bleken"}],
      correctId:"c" },
    { id:"ku14", text:"Hva er en skisse?",
      options:[{id:"a",label:"Ferdig maleri"},{id:"b",label:"Rask utkast/forarbeid"},{id:"c",label:"Skulptur i stein"},{id:"d",label:"Fotografi"}],
      correctId:"b" },
    { id:"ku15", text:"Hvilken teknikk bruker små fargeprikker som blandes av øyet?",
      options:[{id:"a",label:"Pointillisme"},{id:"b",label:"Sfumatoteknikk"},{id:"c",label:"Chiaroscuro"},{id:"d",label:"Impasto"}],
      correctId:"a" },
  ],
  historie: [
    { id:"hi01", text:"Når ble Norge selvstendig fra Sverige (unionsoppløsningen)?",
      options:[{id:"a",label:"1814"},{id:"b",label:"1905"},{id:"c",label:"1945"},{id:"d",label:"1960"}],
      correctId:"b" },
    { id:"hi02", text:"Hvem var Norges konge i 1905?",
      options:[{id:"a",label:"Haakon VII"},{id:"b",label:"Olav V"},{id:"c",label:"Harald V"},{id:"d",label:"Oscar II"}],
      correctId:"a" },
    { id:"hi03", text:"Hvilket år startet første verdenskrig?",
      options:[{id:"a",label:"1912"},{id:"b",label:"1914"},{id:"c",label:"1916"},{id:"d",label:"1918"}],
      correctId:"b" },
    { id:"hi04", text:"Hva het Norges motstandsbevegelse under andre verdenskrig (kjent navn)?",
      options:[{id:"a",label:"Heimevernet"},{id:"b",label:"Milorg"},{id:"c",label:"Hjemmefronten"},{id:"d",label:"Reservepolitiet"}],
      correctId:"b" },
    { id:"hi05", text:"Hvem oppdaget Amerika i 1492 (tradisjonelt svar)?",
      options:[{id:"a",label:"Marco Polo"},{id:"b",label:"Vasco da Gama"},{id:"c",label:"Kristoffer Columbus"},{id:"d",label:"Magellan"}],
      correctId:"c" },
    { id:"hi06", text:"Hva het vikingen som regnes som oppdager av Grønland?",
      options:[{id:"a",label:"Eirik Raude"},{id:"b",label:"Leiv Eiriksson"},{id:"c",label:"Olav Tryggvason"},{id:"d",label:"Harald Hårfagre"}],
      correctId:"a" },
    { id:"hi07", text:"Hvilken by ble delt av en mur fra 1961 til 1989?",
      options:[{id:"a",label:"Praha"},{id:"b",label:"Berlin"},{id:"c",label:"Wien"},{id:"d",label:"Budapest"}],
      correctId:"b" },
    { id:"hi08", text:"Hvilket skip sank i 1912 på sin jomfrutur?",
      options:[{id:"a",label:"Lusitania"},{id:"b",label:"Titanic"},{id:"c",label:"Britannic"},{id:"d",label:"Queen Mary"}],
      correctId:"b" },
    { id:"hi09", text:"Hvilket år ble unionen mellom Danmark og Norge inngått (Kalmarunionen start)?",
      options:[{id:"a",label:"1380"},{id:"b",label:"1397"},{id:"c",label:"1536"},{id:"d",label:"1660"}],
      correctId:"b" },
    { id:"hi10", text:"Hvem var kjent som ‘Jernkansler’ i Tyskland på 1800-tallet?",
      options:[{id:"a",label:"Otto von Bismarck"},{id:"b",label:"Kaiser Wilhelm II"},{id:"c",label:"Ludwig Erhard"},{id:"d",label:"Helmut Kohl"}],
      correctId:"a" },
    { id:"hi11", text:"Hva het den norske kongen som samlet Norge ca. år 872?",
      options:[{id:"a",label:"Olav den Hellige"},{id:"b",label:"Harald Hårfagre"},{id:"c",label:"Håkon den Gode"},{id:"d",label:"Olav Tryggvason"}],
      correctId:"b" },
    { id:"hi12", text:"I hvilket år ble FN (De forente nasjoner) etablert?",
      options:[{id:"a",label:"1919"},{id:"b",label:"1939"},{id:"c",label:"1945"},{id:"d",label:"1955"}],
      correctId:"c" },
    { id:"hi13", text:"Hva het hovedstaden i Romerriket?",
      options:[{id:"a",label:"Athen"},{id:"b",label:"Roma"},{id:"c",label:"Kartago"},{id:"d",label:"Alexandria"}],
      correctId:"b" },
    { id:"hi14", text:"Hvilket land var først ute med månelanding i 1969?",
      options:[{id:"a",label:"Sovjetunionen"},{id:"b",label:"USA"},{id:"c",label:"Kina"},{id:"d",label:"Japan"}],
      correctId:"b" },
    { id:"hi15", text:"Hvem var norsk statsminister under OL på Lillehammer (1994)?",
      options:[{id:"a",label:"Gro Harlem Brundtland"},{id:"b",label:"Kjell Magne Bondevik"},{id:"c",label:"Thorbjørn Jagland"},{id:"d",label:"Jens Stoltenberg"}],
      correctId:"a" },
  ],
  musikk: [
    { id:"mu01", text:"Hvem kalles gjerne «Kongen av pop»?",
      options:[{id:"a",label:"Prince"},{id:"b",label:"Michael Jackson"},{id:"c",label:"Elvis Presley"},{id:"d",label:"The Weeknd"}],
      correctId:"b" },
    { id:"mu02", text:"Hvilket instrument har tangenter og pedaler og finnes ofte i stuer?",
      options:[{id:"a",label:"Orgel"},{id:"b",label:"Piano"},{id:"c",label:"Saksofon"},{id:"d",label:"Klarinett"}],
      correctId:"b" },
    { id:"mu03", text:"Hvilket land kommer bandet a-ha fra?",
      options:[{id:"a",label:"Sverige"},{id:"b",label:"Danmark"},{id:"c",label:"Norge"},{id:"d",label:"Island"}],
      correctId:"c" },
    { id:"mu04", text:"Hvilket instrument har seks strenger i standardoppsett?",
      options:[{id:"a",label:"Fiolin"},{id:"b",label:"Gitar"},{id:"c",label:"Ukulele"},{id:"d",label:"Kontrabass"}],
      correctId:"b" },
    { id:"mu05", text:"Hva heter verdens største strømmetjeneste for musikk (per i dag)?",
      options:[{id:"a",label:"Spotify"},{id:"b",label:"Tidal"},{id:"c",label:"Apple Music"},{id:"d",label:"Deezer"}],
      correctId:"a" },
    { id:"mu06", text:"Hvem komponerte «Til Elise»?",
      options:[{id:"a",label:"Mozart"},{id:"b",label:"Beethoven"},{id:"c",label:"Bach"},{id:"d",label:"Chopin"}],
      correctId:"b" },
    { id:"mu07", text:"Hvilken norsk sangduo består av Chirag og Magdi?",
      options:[{id:"a",label:"Karpe"},{id:"b",label:"Broiler"},{id:"c",label:"Madcon"},{id:"d",label:"Ylvis"}],
      correctId:"a" },
    { id:"mu08", text:"Hva kalles en gruppe på fire musikere?",
      options:[{id:"a",label:"Trió"},{id:"b",label:"Kvartett"},{id:"c",label:"Kvintett"},{id:"d",label:"Sextett"}],
      correctId:"b" },
    { id:"mu09", text:"Hvem sang «Jolene»?",
      options:[{id:"a",label:"Dolly Parton"},{id:"b",label:"Shania Twain"},{id:"c",label:"Taylor Swift"},{id:"d",label:"Kacey Musgraves"}],
      correctId:"a" },
    { id:"mu10", text:"Hvilket norsk program velger bidrag til Eurovision?",
      options:[{id:"a",label:"The Voice"},{id:"b",label:"Stjernekamp"},{id:"c",label:"Melodi Grand Prix"},{id:"d",label:"Allsang på Grensen"}],
      correctId:"c" },
    { id:"mu11", text:"Hvilket instrument er kjent som ‘kongen av instrumentene’ i kirker?",
      options:[{id:"a",label:"Piano"},{id:"b",label:"Orgel"},{id:"c",label:"Fiolin"},{id:"d",label:"Trompet"}],
      correctId:"b" },
    { id:"mu12", text:"Hvem står bak albumet «Thriller»?",
      options:[{id:"a",label:"Prince"},{id:"b",label:"Michael Jackson"},{id:"c",label:"Madonna"},{id:"d",label:"Whitney Houston"}],
      correctId:"b" },
    { id:"mu13", text:"Hva er typisk instrument i folkemusikk med strenger og bue?",
      options:[{id:"a",label:"Hardingfele"},{id:"b",label:"Banjo"},{id:"c",label:"Mandolin"},{id:"d",label:"Sitar"}],
      correctId:"a" },
    { id:"mu14", text:"Hvilket band ga ut «Bohemian Rhapsody»?",
      options:[{id:"a",label:"Queen"},{id:"b",label:"The Beatles"},{id:"c",label:"Rolling Stones"},{id:"d",label:"ABBA"}],
      correctId:"a" },
    { id:"mu15", text:"Hva heter Norges nasjonalsang?",
      options:[{id:"a",label:"Gud signe vårt dyre fedreland"},{id:"b",label:"Ja, vi elsker dette landet"},{id:"c",label:"Mitt lille land"},{id:"d",label:"Norge i rødt, hvitt og blått"}],
      correctId:"b" },
  ],
};

export function lightningBank(cat: "sport" | "kunst" | "historie" | "musikk") {
  return LIGHTNING_BANKS[cat];
}
