const fs = require('fs');
const path = require('path');

const dir = 'assets/coats';
const files = fs.readdirSync(dir)
  .filter(f => f.toLowerCase().endsWith('.png'))
  .sort((a, b) => a.localeCompare(b));

const entries = files.map(f => {
  const key = f.replace(/\.png$/i, '').toLowerCase();
  return `  "${key}": require("@/assets/coats/${f}")`;
});

const out =
  '// AUTO-GENERATED by scripts/gen_coat_images.cjs\n' +
  'export const COAT_IMAGES: Record<string, any> = {\n' +
  entries.join(',\n') +
  '\n};\n\n' +
  'export type CoatKey = keyof typeof COAT_IMAGES;\n';

fs.writeFileSync('src/data/coat_images.ts', out, 'utf8');
console.log('Wrote src/data/coat_images.ts with ' + files.length + ' entries');
